allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@mantine/core@9.5.0'
  - '@mantine/hooks@9.5.0'
  - '@mantine/notifications@9.5.0'
  - '@mantine/store@9.5.0'
  - globals@17.8.0
  - '@types/node@26.1.2'
  - '@vitejs/plugin-react@6.0.5'
  - vite@8.2.0
